spring.application.name=agendamento

spring.datasource.url=jdbc:postgresql://localhost:5432/quadras
spring.datasource.username=postgres
spring.datasource.password=devdbquadras

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true